"use client"

import { useState, useRef, useEffect } from "react"
import { Send, User, Scale, AlertCircle } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card } from "@/components/ui/card"
import { ScrollArea } from "@/components/ui/scroll-area"

type Message = {
  role: "user" | "assistant"
  content: string
}

export default function ChatPage() {
  const [messages, setMessages] = useState<Message[]>([
    { role: "assistant", content: "Hello! I am your Legal AI assistant powered by advanced RAG technology. How can I help you today?" }
  ])
  const [input, setInput] = useState("")
  const [isLoading, setIsLoading] = useState(false)
  const bottomRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" })
  }, [messages])

  const handleSend = async () => {
    if (!input.trim() || isLoading) return

    const userMsg = input.trim()
    setInput("")
    setMessages(prev => [...prev, { role: "user", content: userMsg }])
    setIsLoading(true)

    try {
      const response = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          messages: [...messages, { role: "user", content: userMsg }],
          chat_id: "default-session"
        })
      })
      
      if (!response.ok) throw new Error("Failed to fetch")
      const data = await response.json()
      
      setMessages(prev => [...prev, { role: "assistant", content: data.content }])
    } catch (error) {
      setMessages(prev => [...prev, { role: "assistant", content: "I'm sorry, I'm having trouble connecting to the backend server. Please ensure the Python backend is running." }])
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="container mx-auto px-4 py-8 flex-1 flex flex-col h-[calc(100vh-8rem)]">
      <div className="mb-6">
        <h1 className="text-3xl font-bold text-navy-900">Legal AI Chat</h1>
        <p className="text-slate-600">Ask questions about Indian law, procedures, and rights.</p>
        <div className="mt-2 flex bg-amber-50 text-amber-800 p-3 rounded-md text-sm">
          <AlertCircle className="h-5 w-5 mr-2 shrink-0" />
          <p>Responses are generated by AI and do not constitute formal legal advice. Please consult a qualified lawyer for serious legal matters.</p>
        </div>
      </div>

      <Card className="flex-1 flex flex-col shadow-md overflow-hidden border-slate-200">
        <ScrollArea className="flex-1 p-4">
          <div className="space-y-6">
            {messages.map((message, i) => (
              <div key={i} className={`flex ${message.role === "user" ? "justify-end" : "justify-start"}`}>
                <div className={`flex max-w-[80%] gap-3 items-start ${message.role === "user" ? "flex-row-reverse" : "flex-row"}`}>
                  <div className={`h-8 w-8 rounded-full flex items-center justify-center shrink-0 ${message.role === "user" ? "bg-teal-600" : "bg-slate-800"}`}>
                    {message.role === "user" ? <User className="h-4 w-4 text-white" /> : <Scale className="h-4 w-4 text-white" />}
                  </div>
                  <div className={`rounded-xl p-4 ${message.role === "user" ? "bg-teal-600 text-white" : "bg-slate-100 text-slate-800"}`}>
                    <p className="whitespace-pre-wrap text-sm leading-relaxed">{message.content}</p>
                  </div>
                </div>
              </div>
            ))}
            {isLoading && (
              <div className="flex justify-start">
                <div className="flex gap-3 items-start">
                  <div className="h-8 w-8 rounded-full bg-slate-800 flex items-center justify-center shrink-0">
                    <Scale className="h-4 w-4 text-white" />
                  </div>
                  <div className="rounded-xl p-4 bg-slate-100 text-slate-800">
                    <div className="flex space-x-1">
                      <div className="h-2 w-2 bg-slate-400 rounded-full animate-bounce delay-75"></div>
                      <div className="h-2 w-2 bg-slate-400 rounded-full animate-bounce delay-150"></div>
                      <div className="h-2 w-2 bg-slate-400 rounded-full animate-bounce delay-300"></div>
                    </div>
                  </div>
                </div>
              </div>
            )}
            <div ref={bottomRef} />
          </div>
        </ScrollArea>
        <div className="p-4 border-t bg-slate-50">
          <form 
            onSubmit={(e) => { e.preventDefault(); handleSend(); }}
            className="flex items-center space-x-2"
          >
            <Input 
              value={input} 
              onChange={e => setInput(e.target.value)} 
              placeholder="Ask a legal question..." 
              className="flex-1 h-12 bg-white"
              disabled={isLoading}
            />
            <Button type="submit" size="icon" className="h-12 w-12 bg-teal-600 hover:bg-teal-700" disabled={isLoading || !input.trim()}>
              <Send className="h-5 w-5" />
            </Button>
          </form>
        </div>
      </Card>
    </div>
  )
}
